<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Intra</AssemblyName>
    <RootNamespace>Intra</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FormEventHandler\FormEventHandler.csproj" />
  </ItemGroup>

</Project>
